# --- Moshi -------------------------------------------------------------------
# Adapters are generated by moshi-kotlin-codegen (KSP), so no reflection is used
# at runtime. Moshi still looks the generated adapter up by name, so both the
# annotated model and its *JsonAdapter must survive shrinking. Missing keeps here
# are silent: parsing throws, callers swallow it, and the app just shows no data.
-keep @com.squareup.moshi.JsonClass class * { *; }
-if @com.squareup.moshi.JsonClass class *
-keep class <1>JsonAdapter {
    <init>(...);
    <fields>;
}
-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}
-keep class kotlin.Metadata { *; }

# JSON-backed models: network DTOs, Room entities, and the bundled seed lists.
-keep class com.iurie.etfwatch.data.remote.** { *; }
-keep class com.iurie.etfwatch.data.db.** { *; }
-keep class com.iurie.etfwatch.data.seed.** { *; }

# --- OkHttp / Retrofit -------------------------------------------------------
-dontwarn org.bouncycastle.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**
-dontwarn okhttp3.internal.platform.**
-keepattributes Signature, InnerClasses, EnclosingMethod, RuntimeVisibleAnnotations

# --- MPAndroidChart ----------------------------------------------------------
-keep class com.github.mikephil.charting.** { *; }
-dontwarn com.github.mikephil.charting.**
